spring.application.name=BootProj07_LayeredApplication_Mini_Project
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=dbpract
spring.datasource.password=pass123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver