spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: dbpract
    password: pass123
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSourceImpl