spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ntspbms618db
    username: root
    password: Abhi@93076
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource