spring.application.name=BootProj13_ValueAndConfigPropertyResAnnotation
# student info
student.info.name=Abhijeet
student.info.roll-num=101
student.info.age=21
student.info.address=Nagpur

# bank info
bank.balance=50000

student.info.arr=sahil,Abhi,Rohan;
info.list=sahil,Abhi,Rohan,Neha,Tomar

student.info.names[0]=xxx1
student.info.names[1]=xxx2
student.info.names[2]=xxx3
student.info.names[3]=xxx4


student.info.student2.id=23
student.info.student2.name=Abhi
student.info.student2.age=23

student.info.card.id=12
student.info.card.name=khade
student.info.card.age=21